### PR TITLE
Fix double prefixes

### LINKED ISSUE #78: Applies prefix twice on nested sublevel
Because the prefix is applied on open:

https://github.com/Level/subleveldown/blob/42eca3529bac10cdcec632e71ff9d85d775d6592/leveldown.js#L90-L93

So if you open, close and reopen, `self.prefix = subdb.prefix + self.prefix` happens twice.

There are more issues with the open logic (#60, #77), so let's refactor it a bit.

### PR DESCRIPTION
**Pull request by vweevers**
In two situations:

- When reopening a nested sublevel, because on open we add the parent's prefix to the child's prefix. Open twice, and you get a double prefix. Fixed by keeping around the original prefix.
- When having more than 2 nested sublevels. This resulted in subdown wrapping subdown, effectively applying a double prefix to keys. Fixed by tweaking the unwrapping voodoo.

Closes #78. This PR is an alternative to #79, which fixes more issues but is WIP, more invasive and semver-major, while this is semver-patch (with [a caveat](https://github.com/Level/subleveldown/issues/78#issuecomment-539252577)).

### CODE REVIEW

File: leveldown.js [hunk 1]
```diff
@@ -88,8 +89,8 @@ SubDown.prototype._open = function (opts, cb) {
     var subdb = reachdown(self.db, 'subleveldown')
 
     if (subdb && subdb.prefix) {
-      self.prefix = subdb.prefix + self.prefix
-      self.leveldown = reachdown(subdb.db, matchdown, false)
+      self.prefix = subdb.prefix + self.ownPrefix
+      self.leveldown = subdb.leveldown || reachdown(subdb.db, matchdown, false)
```
Comment (vweevers) [inline leveldown.js]: We should only need 1 one of these solutions (either `subdb.leveldown` or `reachdown(..)`), not sure which I like best.

Comment (vweevers) [reply leveldown.js]: Gonna go with `subdb.leveldown` because `reachdown(sub.db)` is like taking a detour (it goes: own levelup -> encoding-down -> subleveldown -> external levelup -> encoding-down -> leveldown).

**Comment by MeirionHughes** [comment]
I've approved solely on the basis you've added a unit test for the case - I'm afraid I don't know the ramifications of the choice you outlined above; the best I can suggest is whether one approach is better at handling "exotic" subdowns. i.e. `sub(encryptdown(sub(db, "foo"), "bar")` etc...

**Comment by vweevers** [comment]
@MeirionHughes Roger, thanks. We support those exotic situations since 4.1.3 and have a test for it :)
